Add video support
caravelahc/pico-bot pull request #34
Opened 2022-04-16 13:12 UTC by armpico

This PR adds support to video stickers

2022-04-21 01:13 UTC, JPTIZ requested changes
:P I know you're working on some of these comments, but it is good to register them.

2022-04-21 01:13 UTC, JPTIZ commented on picobot/video_editor.py
> +        .run()
[2] Trying to `/addsticker` a video a second time as the same user makes `ffpmeg` ask to overwrite the file:

```console
File '/home/jptiz/dev/car/pico-bot/picobot/images/vid<my user ID>.webm' already exists. Overwrite? [y/N] y
```

Maybe one of these may work, according to [ffmpeg-python docs](https://kkroening.github.io/ffmpeg-python/#ffmpeg.overwrite_output):

1. Adding `.overwrite_output()` to ffmpeg builder:
```suggestion
        .output(vid_output_path.as_posix(), format='webm', vcodec='libvpx-vp9')
        .overwrite_output()
        .run()
```


2. ***Or*** adding `overwrite_output` kwarg to `.run`:
```suggestion
        .output(vid_output_path.as_posix(), format='webm', vcodec='libvpx-vp9')
        .run(overwrite_output=True)
```

2022-04-21 01:13 UTC, JPTIZ commented on picobot/video_editor.py
> +def estimate_video_sticker_size(width: int, height: int):
[3] Annotate return types as well:

```suggestion
def estimate_video_sticker_size(width: int, height: int) -> tuple[int, int]:
```

2022-04-21 01:13 UTC, JPTIZ commented on picobot/video_editor.py
> +        raise Exception('video duration exceeds limits')
[4] A specific exception type would be more clear and easier to handle (e.g. for `except ValueError`):

```suggestion
        raise ValueError('Video duration exceeds limits')
```

(+ sneaky first letter upper 👀)

2022-04-21 01:13 UTC, JPTIZ commented on picobot/video_editor.py
> +    check_duration(duration)
Hmmm I'm not sure I would split this into a function as it is literally just a simple straight-forward `if`. Personally I would bring the function's code here:

```suggestion
    if duration > 3.0:
            raise ValueError('Video duration exceeds limits')
```

2022-05-31 00:38 UTC, JPTIZ commented
Looks like we need a rebase :P

2022-06-01 23:13 UTC, tarcisioe requested changes

2022-06-01 23:13 UTC, tarcisioe commented on pyproject.toml
> +typed-ast = "^1.5.2"
This seems to be a transitive dependency and most likely shouldn't be here.

2022-06-01 23:13 UTC, tarcisioe commented on picobot/video_editor.py
> +class VideoTooLongError(Exception):
Add a docstring.

2022-06-01 23:13 UTC, tarcisioe commented on picobot/handlers.py
> +class FileTooLargeError(Exception):
Add docstring.

2022-06-01 23:13 UTC, tarcisioe commented on picobot/video_editor.py
> +    width = int(video_stream['width'])
`video_stream` can be None. Check and abort early if this is the case.

2022-06-01 23:13 UTC, tarcisioe commented on picobot/video_editor.py
> +    vid_filename = video_path.name
Unused variable.

2022-06-01 23:13 UTC, tarcisioe commented on picobot/video_editor.py
> +        (
Unnecessary parenthesis.

2022-06-01 23:13 UTC, tarcisioe commented on picobot/video_editor.py
> +        (
Unnecessary parethesis.

2022-06-01 23:13 UTC, tarcisioe commented on picobot/video_editor.py
> +def estimate_video_sticker_size(width: int, height: int) -> tuple[int, int]:
```suggestion
class VideoSize(NamedTuple):
    width: int
    height: int


def estimate_video_sticker_size(candidate_size: VideoSize) -> VideoSize:
```

2022-09-12 16:04 UTC, JPTIZ approved these changes
Moved some comments to issues:
- Files not deleted: https://github.com/caravelahc/pico-bot/issues/39.
- Explicit types in exception handling: https://github.com/caravelahc/pico-bot/issues/40.
- Lint/typing issues: https://github.com/caravelahc/pico-bot/issues/41.

2022-10-16 02:16 UTC, merged